### ISSUE TITLE
VPARAMS missing in recent binutils

### ISSUE THREAD

**Issue by ccaamad** [LLNL/PnMPI#4]
Hi,

I've been trying to build MUST 1.5 (and latest git HEAD) on a centos7 system. make aborts at this point:

```
[ 50%] Building C object patch/CMakeFiles/pnmpi-patch.dir/patch.c.o
/nobackup/issmcd/pp/pnmpi-for-must-1.5/patch/patch.c:234:16: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘VPARAMS’
 void non_fatal VPARAMS ((const char *format, ...))
                ^
/nobackup/issmcd/pp/pnmpi-for-must-1.5/patch/patch.c:243:12: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘VPARAMS’
 void fatal VPARAMS ((const char *format, ...))
            ^
make[2]: *** [patch/CMakeFiles/pnmpi-patch.dir/patch.c.o] Error 1
make[1]: *** [patch/CMakeFiles/pnmpi-patch.dir/all] Error 2
make: *** [all] Error 2
```

It seems that VPARAMS has been removed in recent versions of binutils - please see https://gcc.gnu.org/ml/gcc-patches/2014-01/msg00727.html

Any ideas on how to get this to build on centos7, please?

Thanks,

Mark

**Comment by alehaa** [comment]
Hi Mark!

Please note, that the [PnMPI for MUST v1.5](https://doc.itc.rwth-aachen.de/display/CCP/Project+MUST) is not the same as the one in this repository and MUST is not compatible with this PnMPI yet. We'll use this repository beginning with MUST v1.6.

In the meantime, please see RWTH-HPC/PnMPI@d9765d676c66d9a4c555f897ae11480a232ed399, this will be merged back to this repository soon.

**Comment by ccaamad** [comment]
Brilliant! Many thanks for that :)

I don't suppose you know where the bugs/discussion lists are for GTI and MUST, do you please?

Cheers,

Mark

**Comment by jprotze** [comment]
For bug reports we use the list must-feedback@lists.rwth-aachen.de where MUST developers listen.
We are working on a new release of MUST, that includes fixes for this issue

**Comment by ccaamad** [comment]
Great, thanks :)

Mark
