### ISSUE TITLE
MPI_Address is superseded by MPI_Get_address in MPI-2.0

### ISSUE THREAD

**Issue by napo3943** [LLNL/PnMPI#5]
Hi

I keep running into this error when installing PnMPI with  Intel 16.0.3 and openmpi-2.0.2
```
[  1%] Generating wrapper.h from wrapper.h.w
MATCH FAILED FOR: 'MPI_Aint *address) __attribute__((__deprecated__("MPI_Address is superseded by MPI_Get_address in MPI-2.0"))' in MPI_Address
src/CMakeFiles/pnmpi.dir/build.make:73: recipe for target 'src/wrapper.h' failed
make[2]: *** [src/wrapper.h] Error 1
CMakeFiles/Makefile2:99: recipe for target 'src/CMakeFiles/pnmpi.dir/all' failed
make[1]: *** [src/CMakeFiles/pnmpi.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
```
If you have any insight or solutions for this error please let me know.

Thanks,
Nathan

**Comment by alehaa** [comment]
Hi Nathan,

I think this is not an error of PnMPI, but [wrap](https://github.com/LLNL/wrap). There have been some patches on wrap for`MPI_Aint`. It should be fine to go into the wrap submodule and checkout the latest `fortran-fixes` branch. Before doing a clean rebuild.

**Comment by alehaa** [comment]
@napo3943 could you please check, if you get this error with the source from `v1.7-rc2` branch?

**Comment by napo3943** [comment]
@alehaa Sorry for the delayed response. I was able to get beyond the above error when I replaced wrap.py and copied over WrapConfig.cmake from the ```fortran-fixes``` branch. I also tried the ```v1.7-rc2``` branch and ran into this error
```
CMake Error at CMakeLists.txt:100 (find_package):
  By not providing "FindGitInfo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GitInfo", but
  CMake did not find one.

  Could not find a package configuration file provided by "GitInfo" with any
  of the following names:

    GitInfoConfig.cmake
    gitinfo-config.cmake

  Add the installation prefix of "GitInfo" to CMAKE_PREFIX_PATH or set
  "GitInfo_DIR" to a directory containing one of the above files.  If
  "GitInfo" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

But I think the previous fix will work so I go forward with the wrap.py and WrapConfig.cmake fix.

Thanks,
Nathan

**Comment by alehaa** [comment]
Did you load all submodules? Try `git submodule update --init`.

**Comment by napo3943** [comment]
I had not. Once I did that, it installed perfectly. I didn't run into to the previous error at all.

Thank you,
Nathan

**Comment by alehaa** [comment]
Thanks for the response! :)
